os:
  - linux
  - osx
language: python
python:
  - "3.8"  # 3.8 development branch
# command to install dependencies
install:
  - pip install dask==2021.4.1
  - pip install casadi==3.5.5
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - pytest